require:
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - '**/sandbox/**/*'
    - '**/db/migrate/*'
    - '**/Gemfile.lock'
    - '**/rails'
    - 'cli/**/*.gemspec'
    - '**/dummy/**/*'
    - '**/vendor/**/*'
    - '**/spec_helper.rb'
    - '**/templates/**/*'
