name: AYPEX Snyk
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          ruby: ['3.2']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Gems
        run: |
          bundle exec install

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
